### PR TITLE
RTL direction fixes

### PR DESCRIPTION
**Pull request by kwinto**
This PR fixes some issues for the RTL locales.

# How to test
- open index.html,
-  add dir="rtl" attribute to the html tag
- link chat-components from this PR https://github.com/Cognigy/chat-components/pull/73
- open webchat
- check https://cognigy.visualstudio.com/Cognigy.AI/_workitems/edit/72592 for the success criteria 
- do a sanity check for thing which would be relevant for the RTL language support

### CODE REVIEW

**Comment by sushmi21** [comment]
The chat toggle button itself appears in the left corner. I think this should not be affected.

Screenshot from 2024-07-18 16-29-27

**Comment by sushmi21** [comment]
I remember we talked about switching the position of the icons. The icons are not still not switched. For example, the back button is to the right instead of left.
Screenshot from 2024-07-18 17-17-07

**Comment by kwinto** [comment]
> I remember we talked about switching the position of the icons. The icons are not still not switched. For example, the back button is to the right instead of left. This applies to send button, close button etc. Screenshot from 2024-07-18 17-17-07

It is actually flipped. It is showing now to the "back direction" in RTL :-)

**Comment by kwinto** [comment]
> The chat toggle button itself appears in the left corner. I think this should not be affected.
> 
> Screenshot from 2024-07-18 16-29-27

It should definitely appear on the left.

 In RTL localized websites, everything becomes “flipped” to usual for us direction, even the logotypes and such.

**Comment by sushmi21** [comment]
> > I remember we talked about switching the position of the icons. The icons are not still not switched. For example, the back button is to the right instead of left. This applies to send button, close button etc. Screenshot from 2024-07-18 17-17-07
> 
> It is actually flipped. It is showing now to the "back direction" in RTL :-)

What I meant is the position of the buttons. The group of buttons like (minimize, close and chat options should be on the right) and the back button should be on the left, don't you think?

**Comment by kwinto** [comment]
> > > I remember we talked about switching the position of the icons. The icons are not still not switched. For example, the back button is to the right instead of left. This applies to send button, close button etc. Screenshot from 2024-07-18 17-17-07
> > 
> > 
> > It is actually flipped. It is showing now to the "back direction" in RTL :-)
> 
> What I meant is the position of the buttons. The group of buttons like (minimize, close and chat options should be on the right) and the back button should be on the left, don't you think?

I think you got confused here. Originally, the close button is on the right. Now, in RTL, it is on the left. So we actually have flipped the position.

**Comment by sushmi21** [comment]
> > > > I remember we talked about switching the position of the icons. The icons are not still not switched. For example, the back button is to the right instead of left. This applies to send button, close button etc. Screenshot from 2024-07-18 17-17-07
> > > 
> > > 
> > > It is actually flipped. It is showing now to the "back direction" in RTL :-)
> > 
> > 
> > What I meant is the position of the buttons. The group of buttons like (minimize, close and chat options should be on the right) and the back button should be on the left, don't you think?
> 
> I think you got confused here. Originally, the close button is on the right. Now, in RTL, it is on the left. So we actually have flipped the position.

No, I am not confused. I am saying that we should only flip the chat bubbles but not the icon positions. All icons should stay in their original position, don't you think?

**Review by sushmi21 — APPROVED** [review]

**Pull request merged**
