### PR TITLE
bug/15533-Newlines-in-Content

### PR DESCRIPTION
**Pull request by cbuchwald**
Fixed whitespace for multiline text with wrap

This solves: Issue that say nodes with multiline text were displayed in one line

How to test: Create a flow with a say node with multiple lines of code and view it using the modified webchat. Multiline Text should be displayed in several lines

### CODE REVIEW

**Review by Cesarcs7 — APPROVED** [review]

**Comment by sushmi21** [comment]
It seems to work fine for me even without this change. Also, the file name says 'MarkdownMessageBubble'. So, I am not sure if this is the right file.

**Comment by kwinto** [comment]
lgtm @sushmi21 

this template is used when Webchat is initialised with `enableGenericHTMLStyling: true`. It makes sense to have it in sync with regular template regarding the white-space behaviour.

**Comment by sushmi21** [comment]
> lgtm @sushmi21
> 
> this template is used when Webchat is initialised with `enableGenericHTMLStyling: true`. It makes sense to have it in sync with regular template regarding the white-space behaviour.

Okay, then will approve. thanks :)

**Review by sushmi21 — APPROVED** [review]
It worked for me even if I revert this change. But, will approve this anyway since Dmitrii reconfirmed that this won't break anything else. :)

**Pull request merged**
