### PR TITLE
Disable datepicker plugin

### PR DESCRIPTION
**Pull request by fabclj**
This PR disable datepicker plugin since it will be moved to chat-components repo

### CODE REVIEW

**Review by dshire — COMMENTED** [review]
should we not fully remove this import line as well as the /date-picker plugin folder? or when do you plan on doing that?

**Comment by fabclj** [comment]
> should we not fully remove this import line as well as the /date-picker plugin folder? or when do you plan on doing that?

Actually we should also remove the build command on package.json, and finally remove all related existing files. I would do these changes in a second step, just after we merge the new datepicker on chat-components and we are sure is properly working on all usecases.

**Comment by dshire** [comment]
> > should we not fully remove this import line as well as the /date-picker plugin folder? or when do you plan on doing that?
> 
> Actually we should also remove any reference on the bundle command on package.json, and finally remove all related existing files. I would do these changes in a second step, just after we merge the new datepicker on chat-components and we are sure is properly working on all usecases.

we can do it like that but then please write a reminder or a task for yourself to do that, else we can forget that we have this unused code

**Review by dshire — APPROVED** [review]

**Comment by fabclj** [comment]
> we can do it like that but then please write a reminder or a task for yourself to do that, else we can forget that we have this unused code

I will create a more generic US about plugins and legacy messages code clean-up. I believe we have much more than just datepicker to clean-up on v3 branch.

**Pull request merged**
